jdeath/Hubspace-Homeassistant

custom_components/hubspace/light.py

- Adds error handling when Hubspace can't initialize
- Improves ColorMode handling
- Adds support for Color Temperature
- Adds support for a new device

Improve reliability and add support for additional features

---

custom_components/hubspace/hubspace.py
custom_components/hubspace/light.py

I primarily use "rooms" instead of single devices, so I wrote an implementation that will iterate any rooms by name (typeId == metadevice.room) and populate them into Home Assistant

Added support for rooms from Hubspace

---

custom_components/hubspace/light.py

Add support for color temperature on Fanelee. This device doesn't support arbitrary color temperatures, just 6 specific ones. After selection, identify the closest. Additionally, the color temperature is suffixed with K.

Add support for color temperature on Fanelee

---

sample_data/anonymize_json.py
sample_data/fanelee.json

The script anonymize_json.py can be used to remove identifying information from JSON for sharing.
Sample data file containing 1 home, 2 rooms, and 1 Fanelee device in each room.

Add script to remove identifying information from JSON

---

TestHubspace.py

Per request, change the default mode of operation for TestHubspace to prompt for credentials and dump anonymized server response. Allows for reports from users without the use of debugging inside Home Assistant.

Test hubspace updates

---

custom_components/hubspace/hubspace.py
custom_components/hubspace/light.py

Need to use deviceId, not childId
Fixes #20

Fix Outlet Autodiscover

---

custom_components/hubspace/light.py

Previous code was doing equality checking when it should have been doing assignment.  Fixed, tested, fan works now.  Wife is happy.
6/11: I also found a bug where fan-speed-5 had incorrect values, I fixed them.  This works now.  I'll do more testing with it tomorrow.

DriskolFan Fix

---

custom_components/hubspace/hubspace.py

What we talked about previously in the last PR.

More Driskol fixes

---

custom_components/hubspace/light.py

Fan speed missing zeros

---

custom_components/hubspace/light.py

Fixes for Driskol- assignment vs equality issues, fan speed enumeration issues

Driskol Fixes

---

custom_components/hubspace/hubspace.py
custom_components/hubspace/light.py

- Update Vinwood Fan light control
- Update to provide metadata after discovering devices to fix fan speed control
- Tested all functionality with Driskol Fan and Vinwood Fan

Update Vinwood Fan Light and Fix Fan Speed Control

---

custom_components/hubspace/light.py

No Model Number from Hubspace so used device Class instead

Update New Husky Sprinkler Timer

---

README.md
custom_components/hubspace/const.py

* Add sensors for watts and output-voltage-switch
* Update the readme
Sem-Ver: feature
Let me know if you are good with the README changes and I will get this merged.

Add watt and voltage sensors

---

custom_components/hubspace/light.py
tests/device_dumps/light-a21.json
tests/test_light.py

* Fix an issue where RGB lights would not set the proper state and cause a 40x issue
* Fix an issue where lights would send multiple temperatures and cause a 500 error
Sem-Ver: bugfix

Fix RGB Lights

---

README.md
custom_components/hubspace/anonomyize_data.py
custom_components/hubspace/coordinator.py
custom_components/hubspace/fan.py
tests/test_fan.py
tests/test_light.py
tests/test_lock.py
tests/test_valve.py
tests/utils.py

* Fix an issue where fans were not properly consuming the availability state
Sem-Ver: bugfix
Fixes #93

Fix fans showing unavailable

---

custom_components/hubspace/sensor.py
custom_components/hubspace/switch.py
tests/device_dumps/transformer.json
tests/test_sensor.py
tests/test_switch.py

* Fix an issue where a sensor could produce a UHE when updating the state
* Fix an issue where switches would show the incorrect state
* Fix an issue where switches would be added multiple times
Fix for #97

Transformer fix

---

custom_components/hubspace/fan.py
custom_components/hubspace/light.py
tests/test_fan.py
tests/test_light.py

* Implement a fix for #101
* Update effects to use all effect modes

Light Update

---

custom_components/hubspace/light.py
custom_components/hubspace/manifest.json
tests/device_dumps/rgbw-led-strip.json
tests/test_light.py

Fix for #106 
* Goto HACS within HA
* Click `Hubspace-HomeAssistant`
* Click the triple dots on the top-left
* Click `Update Information`
*  Click the triple dots on the top-left
* Click `Redownload`
* Click `Show beta versions`
* Select `fix-color-temp-identifer`  (apparently I couldnt spell this morning)
* Click `DOWNLOAD`
* Restart HA
Let me know if the issues persist after using this beta version

Fix an issue around color temp

---

custom_components/hubspace/__init__.py
custom_components/hubspace/binary_sensor.py
custom_components/hubspace/const.py
custom_components/hubspace/coordinator.py
tests/device_dumps/freezer.json
tests/test_binary_sensor.py
tests/test_coordinator.py

Fix for #109

---

custom_components/hubspace/binary_sensor.py
custom_components/hubspace/fan.py
custom_components/hubspace/hubspace_entity.py
custom_components/hubspace/light.py
custom_components/hubspace/lock.py
custom_components/hubspace/sensor.py
custom_components/hubspace/switch.py
custom_components/hubspace/valve.py
tests/test_binary_sensor.py
tests/test_fan.py
tests/test_hubspace_entity.py
tests/test_light.py
tests/test_lock.py
tests/test_sensor.py
tests/test_switch.py
tests/test_valve.py

* Create a new class, HubSpaceEntity that standardizes all duplicate code
* Update all objects to inherit from HubSpaceEntity
Sem-Ver: feature

Entity Inheritance

---

README.md
custom_components/hubspace/__init__.py
custom_components/hubspace/manifest.json
custom_components/hubspace/services.py
custom_components/hubspace/services.yaml
custom_components/hubspace/strings.json
custom_components/hubspace/translations/en.json
setup.cfg
tests/test_services.py

* Update aiohubspace to the version that supports sending states
* Re-create the service, send_command. After being sent, Home Assistant is automatically updated.

Add send_command service

---

README.md
custom_components/hubspace/entity.py
custom_components/hubspace/lock.py
custom_components/hubspace/manifest.json
tests/test_lock.py

Fix for #128 
* Update to aiohubspace that fixes an issue around locks being managed
Sem-Ver: bugfix

Fix for locks / #128

---

.github/workflows/ci.yaml
README.md
custom_components/hubspace/bridge.py
custom_components/hubspace/button.py
custom_components/hubspace/config_flow.py
custom_components/hubspace/manifest.json
custom_components/hubspace/strings.json
custom_components/hubspace/translations/en.json
tests/conftest.py
tests/test_config_flow.py

When Hubspace rejects the refresh token it triggers the reauth workflow.
 

Reauth workflow

---

README.md
custom_components/hubspace/__init__.py
custom_components/hubspace/bridge.py
custom_components/hubspace/config_flow.py
custom_components/hubspace/const.py
custom_components/hubspace/manifest.json
tests/conftest.py
tests/test_config_flow.py
tests/test_init.py

* Fix for #145
Sem-Ver: bugfix

Reuse refresh token

---

README.md
custom_components/hubspace/const.py
custom_components/hubspace/entity.py
custom_components/hubspace/manifest.json
custom_components/hubspace/number.py
custom_components/hubspace/select.py
tests/conftest.py
tests/test_number.py
tests/test_select.py

Implementation for #152 
* Goto HACS within HA
* Click `Hubspace-HomeAssistant`
* Click the triple dots on the top-left
* Click `Update Information`
*  Click the triple dots on the top-left
* Click `Redownload`
* Click `Show beta versions`
* Select `dev-fully-implement-exhaust-fans`
* Click `DOWNLOAD`
* Restart HA

Fully implement exhaust fans

---

custom_components/hubspace/manifest.json
requirements.txt
tests/device_dumps/light-with-speaker.json
tests/test_switch.py

Add a test to ensure a light with toggles works correctly
